"""Pydantic schemas for LLM-Assisted Automated Code Review."""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from app.domain.enums import CommentStatus


class SeverityEnum(StrEnum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MINOR = "MINOR"
    INFO = "INFO"


class FindingCategoryEnum(StrEnum):
    LOGIC_BUG = "LOGIC_BUG"
    SECURITY_VULNERABILITY = "SECURITY_VULNERABILITY"
    PERFORMANCE_DEGRADATION = "PERFORMANCE_DEGRADATION"
    MAINTAINABILITY = "MAINTAINABILITY"
    FALSE_POSITIVE_OVERRIDE = "FALSE_POSITIVE_OVERRIDE"


class TriangulationStatusEnum(StrEnum):
    CONFIRMED = "CONFIRMED"
    FALSE_POSITIVE_SUPPRESSED = "FALSE_POSITIVE_SUPPRESSED"
    NEW_SEMANTIC_FINDING = "NEW_SEMANTIC_FINDING"


class SuggestedDiff(BaseModel):
    """Represents an actionable replacement code patch."""

    file_path: str
    line_start: int
    line_end: int
    original_code: str
    replacement_code: str
    unified_diff: str = Field(description="Unified git diff format (- / +)")
    explanation: str = Field(description="Why this patch resolves the issue")


class CodeReviewFinding(BaseModel):
    """Detailed code review finding generated by the hybrid AI engine."""

    title: str = Field(description="Concise summary of the finding")
    category: FindingCategoryEnum
    severity: SeverityEnum
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence in finding from 0.0 to 1.0")
    file_path: str
    line_start: int
    line_end: int
    ast_symbol: str | None = Field(default=None, description="Enclosing class, function, or method")
    issue_description: str = Field(description="Technical root cause analysis")
    remediation_advice: str = Field(description="Actionable developer guidance")
    suggested_fix: SuggestedDiff | None = None
    triangulation_status: TriangulationStatusEnum = TriangulationStatusEnum.CONFIRMED
    triangulation_rationale: str | None = Field(
        default=None,
        description="Reasoning for confirming or overriding static/ML flags",
    )
    rule_id: str | None = Field(default=None, description="Associated static rule ID if applicable")


class PullRequestReviewOutput(BaseModel):
    """Complete structured output produced by the LLM reviewer."""

    summary: str = Field(description="High-level architectural assessment of reviewed changes")
    overall_quality_assessment: str = Field(description="Quality grade and maintainability evaluation")
    predicted_risk_level: str = Field(description="CRITICAL, HIGH, MODERATE, or LOW")
    findings: list[CodeReviewFinding] = Field(default_factory=list)


class ReviewCommentResponse(BaseModel):
    """Response model for review comments persisted in the database."""

    model_config = ConfigDict(from_attributes=True)

    id: str
    report_id: str
    file_path: str
    line_number: int
    comment: str
    suggested_patch: str | None = None
    status: CommentStatus
    created_at: datetime
